import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Questrial,
  Inter,
  Jost,
  Reem_Kufi,
  Cedarville_Cursive,
} from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const questrialFont = Questrial({
  weight: "400",
  variable: "--font-questrial",
  subsets: ["latin"],
});
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
});
const reemKufiFun = Reem_Kufi({
  variable: "--font-reem-kufi",
  subsets: ["latin"],
});
const cedarvilleCursive = Cedarville_Cursive({
  weight: "400",
  variable: "--font-cedarville-cursive",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${questrialFont.variable} ${inter.variable} ${jost.variable} ${reemKufiFun.variable} ${cedarvilleCursive.variable} antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
